# Usar la imagen de Nginx
FROM nginx:latest

# Copiar la configuración de Nginx
COPY ./build/nginx/default.conf /etc/nginx/conf.d/

# Crear el directorio /var/www/wordpress
RUN mkdir -p /var/www/wordpress

# Cambiar el propietario de los directorios y archivos relevantes a www-data
RUN touch /var/run/nginx.pid && \
    chown -R www-data:www-data /var/run/nginx.pid && \
    chown -R www-data:www-data /var/cache/nginx && \
    chown -R www-data:www-data /var/www/wordpress && \
    chown -R www-data:www-data /var/log/nginx

# Establecer www-data como el usuario para ejecutar procesos
USER www-data

# Iniciar Nginx en modo foreground
CMD ["nginx", "-g", "daemon off;"]
