version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - ./wordpress/:/var/www/wordpress/
    ports:
      - "8002:80"
    depends_on:
      - php
      - mysql
    networks:
      - wordpress
  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    environment:
      APP_ENV: dev
    volumes:
      - ./wordpress/:/var/www/wordpress/
    networks:
      - wordpress
    depends_on:
      - mysql
    command: php-fpm -F
  mysql:
    image: mysql
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
      ]
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3307:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - wordpress
  phpMyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 8081:80
    networks:
      - wordpress
    depends_on:
      - mysql
networks:
  wordpress:
